on: [push, pull_request]

name: Continuous integration

jobs:
  Tests:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        toolchain:
          - 1.29.0
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Pin serde dependencies if rust 1.29
        if: matrix.toolchain == '1.29.0'
        run: cargo generate-lockfile --verbose && cargo update -p byteorder --precise "1.3.4" && cargo update --package 'serde_json' --precise '1.0.39' && cargo update --package 'serde' --precise '1.0.98' && cargo update --package 'serde_derive' --precise '1.0.98'
      - name: Running tests on ${{ matrix.toolchain }}
        if: matrix.toolchain != '1.29.0' || matrix.os != 'windows-latest'
        run: cargo test --verbose --all-features
